name: Monsters card tests   

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Updated to a more recent Node.js version

      - name: Install dependencies for the project
        run: npm install
        working-directory: ./

      - name: Start the project
        run: npm start &
        working-directory: ./

      - name: Wait for the project to be ready
        run: sleep 30

      - name: Install Cypress
        run: npm install cypress
        working-directory: ./

      - name: Run Cypress tests
        run: npx cypress run
        working-directory: ./

      - name: Upload Cypress videos
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: cypress-videos
          path: ./cypress/videos

      - name: Upload Cypress screenshots
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: cypress-screenshots
          path: ./cypress/screenshots
