name: Monsters card tests   

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 20 */3 * *'

jobs:
  run-tests:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false # https://github.com/cypress-io/github-action/issues/48
      matrix:
        node-version: [ 22.x ] # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        browser: [ chrome, firefox ]

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Updated to a more recent Node.js version

      - name: Install dependencies for the project
        run: npm install
        working-directory: frontend

      - name: Start the project
        run: npm start &
        working-directory: frontend

      - name: Wait for the project to be ready
        run: sleep 30

      - name: Install Cypress
        run: npm install cypress
        working-directory: ./

      - name: Run Cypress Tests
        run: |
          npx cypress run \
            --record \
            --key eec2f54c-de1d-4cdf-9efa-bcf45a7fc51c \
            --parallel \
            --group "browser-${{ matrix.browser }}" \
            --browser ${{ matrix.browser }}   

      - name: Run Cypress tests
        run: npx cypress run
        working-directory: ./

     